name: msDecor
description: A Minecraft plugin with Decorations for "Unknown server"
authors: [MinersStudios, p0loskun]
website: <a href="http://minersstudios.github.io/" class="external free" rel="nofollow">http://minersstudios.github.io/</a>

version: ${project.version}
main: github.minersStudios.msDecor.Main
api-version: 1.18
database: false
softdepend:
  - CoreProtect